from __future__ import annotations

import argparse
import json
import sys
import threading
import urllib.error
import urllib.request
from dataclasses import dataclass
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import unquote, urlparse


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
SIMULATION_PLAYBACK_STATE_SAMPLE_PATH = REPOSITORY_ROOT / "platform" / "contracts" / "simulation_playback_state_sample.json"
REPORTS_ROOT = REPOSITORY_ROOT / "analysis" / "reports"
CONTRACTS_ROOT = REPOSITORY_ROOT / "platform" / "contracts"


@dataclass(frozen=True)
class ReportDefinition:
    report_id: str
    title: str
    category: str
    description: str
    artifact_path: Path
    markdown_path: Path
    quality_check_path: Path


REPORT_DEFINITIONS: tuple[ReportDefinition, ...] = (
    ReportDefinition(
        report_id="project_status",
        title="Project status",
        category="engineering",
        description="Current structural engineering status.",
        artifact_path=REPORTS_ROOT / "project_status_report.json",
        markdown_path=REPORTS_ROOT / "project_status_report.md",
        quality_check_path=REPORTS_ROOT / "project_status_quality_check.json",
    ),
    ReportDefinition(
        report_id="campaign_final_diagnostic_report",
        title="Campaign final diagnostic report",
        category="campaign analysis",
        description="Final diagnostic report generated by the experimental campaign pipeline.",
        artifact_path=REPORTS_ROOT / "campaign_final_diagnostic_report.json",
        markdown_path=REPORTS_ROOT / "campaign_final_diagnostic_report.md",
        quality_check_path=REPORTS_ROOT / "campaign_final_diagnostic_report_quality_check.json",
    ),
    ReportDefinition(
        report_id="full_campaign_pipeline_manifest",
        title="Full campaign pipeline manifest",
        category="campaign analysis",
        description="Execution manifest for the generated campaign analysis pipeline.",
        artifact_path=REPORTS_ROOT / "full_campaign_pipeline_manifest.json",
        markdown_path=REPORTS_ROOT / "full_campaign_pipeline_manifest.md",
        quality_check_path=REPORTS_ROOT / "full_pipeline_quality_check.json",
    ),
)

REPORT_DEFINITION_BY_ID = {
    report.report_id: report
    for report in REPORT_DEFINITIONS
}


def _relative_path(path: Path) -> str:
    try:
        return path.relative_to(REPOSITORY_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def _read_json_file(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}

    with path.open("r", encoding="utf-8") as file:
        payload = json.load(file)

    if isinstance(payload, dict):
        return payload

    return {"value": payload}


def _read_text_file(path: Path, max_characters: int = 12000) -> str:
    if not path.exists():
        return ""

    text = path.read_text(encoding="utf-8")
    return text[:max_characters]


def _top_level_keys(payload: dict[str, Any]) -> list[str]:
    return sorted(str(key) for key in payload.keys())


def _quality_check_passed(payload: dict[str, Any]) -> bool:
    if not payload:
        return False

    direct_values = [
        payload.get("passed"),
        payload.get("quality_check_passed"),
        payload.get("success"),
        payload.get("ok"),
    ]

    if any(value is True for value in direct_values):
        return True

    status_values = [
        payload.get("status"),
        payload.get("result"),
        payload.get("quality_status"),
    ]

    return any(str(value).lower() == "passed" for value in status_values)


def _report_catalog_item(report: ReportDefinition) -> dict[str, Any]:
    quality_payload = _read_json_file(report.quality_check_path)
    quality_passed = _quality_check_passed(quality_payload)

    return {
        "id": report.report_id,
        "report_id": report.report_id,
        "title": report.title,
        "category": report.category,
        "description": report.description,
        "artifact_path": _relative_path(report.artifact_path),
        "artifactPath": _relative_path(report.artifact_path),
        "markdown_path": _relative_path(report.markdown_path),
        "markdownPath": _relative_path(report.markdown_path),
        "quality_check_path": _relative_path(report.quality_check_path),
        "qualityCheckPath": _relative_path(report.quality_check_path),
        "quality_status": "passed" if quality_passed else "not available",
        "qualityStatus": "passed" if quality_passed else "not available",
        "available": report.artifact_path.exists(),
        "read_only": True,
        "execution_enabled": False,
        "detail_endpoint": f"/api/v1/reports/{report.report_id}",
        "detailEndpoint": f"/api/v1/reports/{report.report_id}",
    }


def _report_detail(report: ReportDefinition) -> dict[str, Any]:
    artifact_payload = _read_json_file(report.artifact_path)
    quality_payload = _read_json_file(report.quality_check_path)
    markdown_preview = _read_text_file(report.markdown_path)
    quality_passed = _quality_check_passed(quality_payload)

    return {
        "id": report.report_id,
        "report_id": report.report_id,
        "title": report.title,
        "category": report.category,
        "description": report.description,
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "browser_triggered_execution_enabled": False,
        "artifact_path": _relative_path(report.artifact_path),
        "markdown_path": _relative_path(report.markdown_path),
        "quality_check_path": _relative_path(report.quality_check_path),
        "quality_status": "passed" if quality_passed else "not available",
        "artifact_top_level_keys": _top_level_keys(artifact_payload),
        "artifact": {
            "path": _relative_path(report.artifact_path),
            "available": report.artifact_path.exists(),
            "top_level_keys": _top_level_keys(artifact_payload),
            "content": artifact_payload,
        },
        "artifact_json": artifact_payload,
        "markdown": {
            "path": _relative_path(report.markdown_path),
            "available": report.markdown_path.exists(),
            "preview": markdown_preview,
        },
        "markdown_preview": markdown_preview,
        "quality_check": {
            "path": _relative_path(report.quality_check_path),
            "available": report.quality_check_path.exists(),
            "passed": quality_passed,
            "content": quality_payload,
        },
        "quality_check_json": quality_payload,
        "safety_note": (
            "This endpoint is inspection-only. It does not execute experiments, "
            "solvers, scripts, commands, or backend jobs."
        ),
    }


def _reports_catalog_payload() -> dict[str, Any]:
    reports = [_report_catalog_item(report) for report in REPORT_DEFINITIONS]
    categories = sorted({str(report["category"]) for report in reports})

    return {
        "schema": "fieldops_lab.read_only_report_catalog",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "reports": reports,
        "categories": categories,
        "total_reports": len(reports),
        "campaign_report_count": sum(
            1
            for report in reports
            if str(report["category"]).lower() == "campaign analysis"
        ),
    }


def _project_status_payload() -> dict[str, Any]:
    payload = _read_json_file(REPORTS_ROOT / "project_status_report.json")

    return {
        "schema": "fieldops_lab.project_status_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "project_status": payload,
        "artifact_path": "analysis/reports/project_status_report.json",
    }


def _experimental_design_payload() -> dict[str, Any]:
    payload = _read_json_file(REPORTS_ROOT / "experimental_design_matrix.json")

    return {
        "schema": "fieldops_lab.experimental_design_matrix_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "experimental_design_matrix": payload,
        "artifact_path": "analysis/reports/experimental_design_matrix.json",
    }


def _research_method_payload() -> dict[str, Any]:
    return {
        "schema": "fieldops_lab.research_method_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "method_summary": {
            "platform_goal": (
                "Develop FieldOps Lab as an experimental platform for dynamic "
                "TRSP/WSRP field operations."
            ),
            "dissertation_focus": (
                "Keep the academic contribution focused on delays, especially "
                "delay propagation and replanning policy comparison."
            ),
            "future_expansion": [
                "new_requests",
                "cancellations",
                "priority_changes",
            ],
        },
    }


def _simulation_state_contract_payload() -> dict[str, Any]:
    payload = _read_json_file(CONTRACTS_ROOT / "simulation_state_contract.json")

    return {
        "schema": "fieldops_lab.simulation_state_contract_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "browser_triggered_execution_enabled": False,
        "simulation_state_contract": payload,
        "artifact_path": "platform/contracts/simulation_state_contract.json",
    }


def _simulation_state_sample_payload() -> dict[str, Any]:
    payload = _read_json_file(CONTRACTS_ROOT / "simulation_state_sample.json")

    return {
        "schema": "fieldops_lab.simulation_state_sample_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "browser_triggered_execution_enabled": False,
        "simulation_state_sample": payload,
        "artifact_path": "platform/contracts/simulation_state_sample.json",
        "safety_note": (
            "This endpoint exposes a static sample state for read-only map and "
            "timeline inspection. It does not start simulation jobs."
        ),
    }


def _delay_injection_request_contract_payload() -> dict[str, Any]:
    payload = _read_json_file(CONTRACTS_ROOT / "delay_injection_request_contract.json")
    planned_endpoint = payload.get("planned_endpoint", {})

    return {
        "schema": "fieldops_lab.delay_injection_request_contract_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "browser_triggered_execution_enabled": False,
        "delay_injection_request_contract": payload,
        "planned_endpoint": planned_endpoint,
        "artifact_path": "platform/contracts/delay_injection_request_contract.json",
        "safety_note": (
            "This endpoint exposes the delay injection request contract for inspection. "
            "It does not inject delays, run solvers, start simulations, write files, "
            "or trigger backend jobs."
        ),
    }


def _replanning_decision_response_contract_payload() -> dict[str, Any]:
    payload = _read_json_file(
        CONTRACTS_ROOT / "replanning_decision_response_contract.json"
    )
    future_endpoint = payload.get("future_endpoint", {})

    return {
        "schema": "fieldops_lab.replanning_decision_response_contract_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "browser_triggered_execution_enabled": False,
        "replanning_decision_response_contract": payload,
        "future_endpoint": future_endpoint,
        "planned_endpoint": future_endpoint,
        "artifact_path": "platform/contracts/replanning_decision_response_contract.json",
        "safety_note": (
            "This endpoint exposes the future re-planning decision response contract "
            "for inspection. It does not execute re-planning decisions, run solvers, "
            "start optimization, start simulation jobs, write files, or trigger backend jobs."
        ),
    }



def _replanning_decision_response_sample_payload() -> dict[str, Any]:
    payload = _read_json_file(
        CONTRACTS_ROOT / "replanning_decision_response_sample.json"
    )
    return {
        "schema": "fieldops_lab.replanning_decision_response_sample_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "browser_triggered_execution_enabled": False,
        "replanning_decision_response_sample": payload,
        "sample_id": payload.get("sample_id"),
        "decision_summary": payload.get("decision_summary", {}),
        "delay_propagation": payload.get("delay_propagation", {}),
        "tradeoff_summary": payload.get("tradeoff_summary", {}),
        "artifact_path": "platform/contracts/replanning_decision_response_sample.json",
        "safety_note": (
            "This endpoint exposes a static read-only sample of a future "
            "re-planning decision response. It does not execute re-planning, "
            "run solvers, start optimization, start simulations, mutate schedules, "
            "write files, or trigger backend jobs."
        ),
    }


def _simulation_playback_control_contract_payload() -> dict[str, Any]:
    payload = _read_json_file(CONTRACTS_ROOT / "simulation_playback_control_contract.json")
    future_endpoint = payload.get("future_endpoint", {})
    return {
        "schema": "fieldops_lab.simulation_playback_control_contract_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "browser_triggered_execution_enabled": False,
        "simulation_playback_control_contract": payload,
        "future_endpoint": future_endpoint,
        "planned_endpoint": future_endpoint,
        "artifact_path": "platform/contracts/simulation_playback_control_contract.json",
        "safety_note": (
            "This endpoint exposes the future simulation playback control contract "
            "for inspection. It does not play, pause, step, seek, start simulation "
            "execution, inject delays, run solvers, trigger re-planning, write files, "
            "or mutate backend state."
        ),
    }

def _solver_integration_contract_payload() -> dict[str, Any]:
    payload = _read_json_file(CONTRACTS_ROOT / "solver_integration_contract.json")

    return {
        "schema": "fieldops_lab.solver_integration_contract_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "browser_triggered_execution_enabled": False,
        "solver_integration_contract": payload,
        "artifact_path": "platform/contracts/solver_integration_contract.json",
        "safety_note": (
            "This endpoint exposes the solver integration contract for inspection. "
            "It does not execute OR-Tools, Gurobi, optimization jobs, simulation jobs, "
            "policy comparison jobs, scripts, commands, file writes, or backend mutations."
        ),
    }



def _comparative_analysis_contract_payload() -> dict[str, Any]:
    payload = _read_json_file(CONTRACTS_ROOT / "comparative_analysis_contract.json")

    return {
        "schema": "fieldops_lab.comparative_analysis_contract_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "browser_triggered_execution_enabled": False,
        "comparative_analysis_contract": payload,
        "artifact_path": "platform/contracts/comparative_analysis_contract.json",
        "safety_note": (
            "This endpoint exposes the comparative analysis contract for inspection. "
            "It does not execute campaigns, run solvers, compute statistical tests, "
            "write files, mutate schedules, or trigger backend jobs."
        ),
    }


def _comparative_analysis_sample_payload() -> dict[str, Any]:
    payload = _read_json_file(CONTRACTS_ROOT / "comparative_analysis_sample.json")

    return {
        "schema": "fieldops_lab.comparative_analysis_sample_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "browser_triggered_execution_enabled": False,
        "comparative_analysis_sample": payload,
        "sample_id": payload.get("sample_id"),
        "runtime_status": payload.get("runtime_status", {}),
        "research_alignment": payload.get("research_alignment", {}),
        "comparison_unit": payload.get("comparison_unit", {}),
        "candidate_policies": payload.get("candidate_policies", []),
        "metrics": payload.get("metrics", {}),
        "sample_results": payload.get("sample_results", []),
        "statistical_analysis_plan": payload.get("statistical_analysis_plan", {}),
        "sample_ranking": payload.get("sample_ranking", []),
        "decision_framework_output": payload.get("decision_framework_output", {}),
        "artifact_path": "platform/contracts/comparative_analysis_sample.json",
        "safety_note": (
            "This endpoint exposes a static read-only comparative analysis sample. "
            "It does not execute experiments, run solvers, run statistical scripts, "
            "mutate schedules, write files, or claim real experimental evidence."
        ),
    }


def _deployment_readiness_contract_payload() -> dict[str, Any]:
    payload = _read_json_file(CONTRACTS_ROOT / "deployment_readiness_contract.json")
    return {
        "schema": "fieldops_lab.deployment_readiness_contract_endpoint",
        "version": "0.1.0",
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "browser_triggered_execution_enabled": False,
        "deployment_execution_enabled": False,
        "deployment_readiness_contract": payload,
        "target_architecture": payload.get("target_architecture", {}),
        "deployment_targets": payload.get("deployment_targets", []),
        "quality_gate_requirements": payload.get("quality_gate_requirements", {}),
        "research_alignment": payload.get("research_alignment", {}),
        "safety_requirements": payload.get("safety_requirements", {}),
        "artifact_path": "platform/contracts/deployment_readiness_contract.json",
        "safety_note": (
            "This endpoint exposes the deployment readiness contract for inspection. "
            "It does not deploy the frontend, deploy the API, run solvers, start jobs, "
            "write files, change cloud resources, or trigger backend execution."
        ),
    }



def _health_payload() -> dict[str, Any]:
    return {
        "schema": "fieldops_lab.read_only_api_health",
        "version": "0.1.0",
        "status": "ok",
        "read_only": True,
        "execution_enabled": False,
        "write_operations_supported": False,
        "browser_triggered_execution_enabled": False,
        "endpoints": [
            "/api/v1/health",
            "/api/v1/project-status",
            "/api/v1/reports",
            "/api/v1/reports/{report_id}",
            "/api/v1/experimental-design-matrix",
            "/api/v1/research-method",
            "/api/v1/simulation-state-contract",
            "/api/v1/simulation-state-sample",
            "/api/v1/delay-injection-request-contract",
            "/api/v1/replanning-decision-response-contract",
            "/api/v1/replanning-decision-response-sample",
            "/api/v1/simulation-playback-control-contract",
            "/api/v1/simulation-playback-state-sample",
            "/api/v1/solver-integration-contract",
            "/api/v1/comparative-analysis-contract",
            "/api/v1/comparative-analysis-sample",
            "/api/v1/deployment-readiness-contract",
        ],
    }


class FieldOpsReadOnlyRequestHandler(BaseHTTPRequestHandler):
    server_version = "FieldOpsLabReadOnlyApi/0.1"

    def log_message(self, format: str, *args: Any) -> None:
        return

    def _send_json(self, status: HTTPStatus, payload: dict[str, Any]) -> None:
        body = json.dumps(payload, indent=2, sort_keys=True).encode("utf-8")

        self.send_response(status.value)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()
        self.wfile.write(body)

    def _send_error_payload(self, status: HTTPStatus, message: str) -> None:
        self._send_json(
            status,
            {
                "status": "error",
                "read_only": True,
                "execution_enabled": False,
                "message": message,
            },
        )

    def do_OPTIONS(self) -> None:
        self.send_response(HTTPStatus.NO_CONTENT.value)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_POST(self) -> None:
        self._send_error_payload(
            HTTPStatus.METHOD_NOT_ALLOWED,
            "This API is read-only. POST requests are not supported.",
        )

    def do_PUT(self) -> None:
        self._send_error_payload(
            HTTPStatus.METHOD_NOT_ALLOWED,
            "This API is read-only. PUT requests are not supported.",
        )

    def do_PATCH(self) -> None:
        self._send_error_payload(
            HTTPStatus.METHOD_NOT_ALLOWED,
            "This API is read-only. PATCH requests are not supported.",
        )

    def do_DELETE(self) -> None:
        self._send_error_payload(
            HTTPStatus.METHOD_NOT_ALLOWED,
            "This API is read-only. DELETE requests are not supported.",
        )

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        path = unquote(parsed.path).rstrip("/") or "/"

        if path == "/api/v1/health":
            self._send_json(HTTPStatus.OK, _health_payload())
            return

        if path == "/api/v1/project-status":
            self._send_json(HTTPStatus.OK, _project_status_payload())
            return

        if path == "/api/v1/reports":
            self._send_json(HTTPStatus.OK, _reports_catalog_payload())
            return

        if path.startswith("/api/v1/reports/"):
            self._handle_report_detail(path)
            return

        if path == "/api/v1/experimental-design-matrix":
            self._send_json(HTTPStatus.OK, _experimental_design_payload())
            return

        if path == "/api/v1/research-method":
            self._send_json(HTTPStatus.OK, _research_method_payload())
            return

        if path == "/api/v1/simulation-state-contract":
            self._send_json(HTTPStatus.OK, _simulation_state_contract_payload())
            return

        if path == "/api/v1/simulation-state-sample":
            self._send_json(HTTPStatus.OK, _simulation_state_sample_payload())
            return

        if path == "/api/v1/delay-injection-request-contract":
            self._send_json(HTTPStatus.OK, _delay_injection_request_contract_payload())
            return

        if path == "/api/v1/replanning-decision-response-contract":
            self._send_json(
                HTTPStatus.OK,
                _replanning_decision_response_contract_payload(),
            )
            return
        if path == "/api/v1/replanning-decision-response-sample":
            self._send_json(
                HTTPStatus.OK,
                _replanning_decision_response_sample_payload(),
            )
            return

        if path == "/api/v1/simulation-playback-control-contract":
            self._send_json(
                HTTPStatus.OK,
                _simulation_playback_control_contract_payload(),
            )
            return

        if path == "/api/v1/solver-integration-contract":
            self._send_json(
                HTTPStatus.OK,
                _solver_integration_contract_payload(),
            )
            return


        if path == "/api/v1/simulation-playback-state-sample":
            self._send_json(
                HTTPStatus.OK,
                _simulation_playback_control_contract_payload(),
            )
            return

        if path == "/api/v1/comparative-analysis-contract":
            self._send_json(
                HTTPStatus.OK,
                _comparative_analysis_contract_payload(),
            )
            return


        if path == "/api/v1/comparative-analysis-sample":
            self._send_json(
                HTTPStatus.OK,
                _comparative_analysis_sample_payload(),
            )
            return
        if path == "/api/v1/deployment-readiness-contract":
            self._send_json(
                HTTPStatus.OK,
                _deployment_readiness_contract_payload(),
            )
            return

        self._send_error_payload(HTTPStatus.NOT_FOUND, "Endpoint not found.")

    def _handle_report_detail(self, path: str) -> None:
        report_id = path.removeprefix("/api/v1/reports/")

        if not report_id or "/" in report_id or "\\" in report_id or ".." in report_id:
            self._send_error_payload(HTTPStatus.NOT_FOUND, "Report not found.")
            return

        report = REPORT_DEFINITION_BY_ID.get(report_id)

        if report is None:
            self._send_error_payload(HTTPStatus.NOT_FOUND, "Report not found.")
            return

        self._send_json(HTTPStatus.OK, _report_detail(report))


def _create_server(host: str, port: int) -> ThreadingHTTPServer:
    return ThreadingHTTPServer((host, port), FieldOpsReadOnlyRequestHandler)


def _read_url_json(url: str, method: str = "GET") -> tuple[int, dict[str, Any]]:
    request = urllib.request.Request(url, method=method)

    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            payload = json.loads(response.read().decode("utf-8"))
            return response.status, payload
    except urllib.error.HTTPError as error:
        try:
            payload = json.loads(error.read().decode("utf-8"))
        finally:
            error.close()

        return error.code, payload


def run_self_test() -> int:
    server = _create_server("127.0.0.1", 0)
    host, port = server.server_address
    base_url = f"http://{host}:{port}"

    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()

    checks = [
        ("/api/v1/health", HTTPStatus.OK),
        ("/api/v1/project-status", HTTPStatus.OK),
        ("/api/v1/reports", HTTPStatus.OK),
        ("/api/v1/reports/project_status", HTTPStatus.OK),
        ("/api/v1/reports/campaign_final_diagnostic_report", HTTPStatus.OK),
        ("/api/v1/experimental-design-matrix", HTTPStatus.OK),
        ("/api/v1/research-method", HTTPStatus.OK),
        ("/api/v1/simulation-state-contract", HTTPStatus.OK),
        ("/api/v1/simulation-state-sample", HTTPStatus.OK),
        ("/api/v1/delay-injection-request-contract", HTTPStatus.OK),
        ("/api/v1/replanning-decision-response-contract", HTTPStatus.OK),
        ("/api/v1/replanning-decision-response-sample", HTTPStatus.OK),
        ("/api/v1/simulation-playback-control-contract", HTTPStatus.OK),
        ("/api/v1/solver-integration-contract", HTTPStatus.OK),
        ("/api/v1/comparative-analysis-contract", HTTPStatus.OK),
        ("/api/v1/comparative-analysis-sample", HTTPStatus.OK),
        ("/api/v1/deployment-readiness-contract", HTTPStatus.OK),
        ("/api/v1/simulation-playback-state-sample", HTTPStatus.OK),
    ]

    try:
        for endpoint, expected_status in checks:
            status, _payload = _read_url_json(base_url + endpoint)
            print(f"{endpoint} {status}")

            if status != expected_status.value:
                return 1

        status, _payload = _read_url_json(base_url + "/api/v1/reports/unknown_report")
        print(f"GET /api/v1/reports/unknown_report {status}")

        if status != HTTPStatus.NOT_FOUND.value:
            return 1

        status, _payload = _read_url_json(base_url + "/api/v1/health", method="POST")
        print(f"POST /api/v1/health {status}")

        if status != HTTPStatus.METHOD_NOT_ALLOWED.value:
            return 1

        print("FieldOps Lab read-only API self-test passed.")
        return 0
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)


def serve(host: str, port: int) -> int:
    server = _create_server(host, port)

    print(f"FieldOps Lab read-only API listening on http://{host}:{port}")
    print("Execution endpoints are disabled.")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down FieldOps Lab read-only API.")
    finally:
        server.server_close()

    return 0


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="FieldOps Lab read-only local HTTP API."
    )
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8080)
    parser.add_argument("--self-test", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)

    if args.self_test:
        return run_self_test()

    return serve(args.host, args.port)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
