from __future__ import annotations

import argparse
import json
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]

PROJECT_STATUS_PATH = (
    REPOSITORY_ROOT / "analysis" / "reports" / "project_status_report.json"
)
REPORTS_ROOT = REPOSITORY_ROOT / "analysis" / "reports"

EXPERIMENTAL_DESIGN_PATH = (
    REPOSITORY_ROOT / "analysis" / "reports" / "experimental_design_matrix.json"
)

PLATFORM_CONTRACT_PATH = (
    REPOSITORY_ROOT / "platform" / "contracts" / "fieldops_platform_contract.json"
)

RESEARCH_METHOD_CONTRACT_PATH = (
    REPOSITORY_ROOT / "platform" / "contracts" / "research_method_contract.json"
)

SIMULATION_STATE_CONTRACT_PATH = (
    REPOSITORY_ROOT / "platform" / "contracts" / "simulation_state_contract.json"
)

RESEARCH_FRAMING_PATH = REPOSITORY_ROOT / "platform" / "research_framing.md"


REPORT_DEFINITIONS: list[dict[str, str]] = [
    {
        "id": "project_status",
        "title": "Project status",
        "category": "engineering",
        "description": "Current structural engineering status.",
        "artifact_path": "analysis/reports/project_status_report.json",
        "markdown_path": "analysis/reports/project_status_report.md",
        "quality_path": "analysis/reports/project_status_quality_check.json",
    },
    {
        "id": "test_inventory",
        "title": "Test inventory",
        "category": "engineering",
        "description": "Current automated test inventory.",
        "artifact_path": "analysis/reports/test_inventory_report.json",
        "markdown_path": "analysis/reports/test_inventory_report.md",
        "quality_path": "analysis/reports/test_inventory_quality_check.json",
    },
    {
        "id": "experimental_design_matrix",
        "title": "Experimental design matrix",
        "category": "scientific_design",
        "description": "Explicit experimental factors, scenarios, and planned replications.",
        "artifact_path": "analysis/reports/experimental_design_matrix.json",
        "markdown_path": "analysis/reports/experimental_design_matrix.md",
        "quality_path": "analysis/reports/experimental_design_matrix_quality_check.json",
    },
    {
        "id": "experiment_campaign_plan",
        "title": "Experiment campaign plan",
        "category": "campaign_planning",
        "description": "Planned experimental campaign structure before execution.",
        "artifact_path": "analysis/reports/experiment_campaign_plan.json",
        "markdown_path": "analysis/reports/experiment_campaign_plan.md",
        "quality_path": "analysis/reports/experiment_campaign_plan_quality_check.json",
    },
    {
        "id": "campaign_index",
        "title": "Campaign index",
        "category": "campaign_planning",
        "description": "Index of the generated campaign artifacts and planned execution units.",
        "artifact_path": "analysis/reports/campaign_index.json",
        "markdown_path": "analysis/reports/campaign_index.md",
        "quality_path": "analysis/reports/campaign_quality_check.json",
    },
    {
        "id": "campaign_decision_matrix",
        "title": "Campaign decision matrix",
        "category": "campaign_analysis",
        "description": "Decision matrix used to connect scenario classes, triggers, and policy evidence.",
        "artifact_path": "analysis/reports/campaign_decision_matrix.json",
        "markdown_path": "analysis/reports/campaign_decision_matrix.md",
        "quality_path": "analysis/reports/campaign_decision_matrix_quality_check.json",
    },
    {
        "id": "campaign_perturbation_plan_index",
        "title": "Campaign perturbation plan index",
        "category": "campaign_planning",
        "description": "Index of perturbation plans used by the experimental campaign.",
        "artifact_path": "analysis/reports/campaign_perturbation_plan_index.json",
        "markdown_path": "analysis/reports/campaign_perturbation_plan_index.md",
        "quality_path": "analysis/reports/campaign_perturbation_plan_quality_check.json",
    },
    {
        "id": "campaign_perturbation_connection",
        "title": "Campaign perturbation connection",
        "category": "campaign_analysis",
        "description": "Connection between campaign scenarios and perturbation structures.",
        "artifact_path": "analysis/reports/campaign_perturbation_connection.json",
        "markdown_path": "analysis/reports/campaign_perturbation_connection.md",
        "quality_path": "analysis/reports/campaign_perturbation_plan_quality_check.json",
    },
    {
        "id": "campaign_execution_index",
        "title": "Campaign execution index",
        "category": "campaign_execution",
        "description": "Index of campaign execution artifacts generated by the current pipeline.",
        "artifact_path": "analysis/reports/campaign_execution_index.json",
        "markdown_path": "analysis/reports/campaign_execution_index.md",
        "quality_path": "analysis/reports/campaign_execution_quality_check.json",
    },
    {
        "id": "campaign_result_summary",
        "title": "Campaign result summary",
        "category": "campaign_analysis",
        "description": "Summary of generated campaign results and diagnostic outputs.",
        "artifact_path": "analysis/reports/campaign_result_summary.json",
        "markdown_path": "analysis/reports/campaign_result_summary.md",
        "quality_path": "analysis/reports/campaign_result_summary_quality_check.json",
    },
    {
        "id": "campaign_ranking_profile_sensitivity",
        "title": "Campaign ranking profile sensitivity",
        "category": "campaign_analysis",
        "description": "Sensitivity of ranking outcomes to profile and weighting assumptions.",
        "artifact_path": "analysis/reports/campaign_ranking_profile_sensitivity.json",
        "markdown_path": "analysis/reports/campaign_ranking_profile_sensitivity.md",
        "quality_path": "analysis/reports/campaign_ranking_profile_sensitivity_quality_check.json",
    },
    {
        "id": "campaign_final_diagnostic_report",
        "title": "Campaign final diagnostic report",
        "category": "campaign_analysis",
        "description": "Final diagnostic report generated by the experimental campaign pipeline.",
        "artifact_path": "analysis/reports/campaign_final_diagnostic_report.json",
        "markdown_path": "analysis/reports/campaign_final_diagnostic_report.md",
        "quality_path": "analysis/reports/campaign_final_diagnostic_report_quality_check.json",
    },
    {
        "id": "full_campaign_pipeline",
        "title": "Full campaign pipeline",
        "category": "pipeline",
        "description": "Manifest, report, and quality check for the full campaign pipeline.",
        "artifact_path": "analysis/reports/full_campaign_pipeline_manifest.json",
        "markdown_path": "analysis/reports/full_campaign_pipeline_report.md",
        "quality_path": "analysis/reports/full_campaign_pipeline_quality_check.json",
    },
    {
        "id": "policy_trigger_behavior_audit",
        "title": "Policy trigger behavior audit",
        "category": "diagnostic",
        "description": "Audit of trigger behavior used to reason about re-planning policy activation.",
        "artifact_path": "analysis/reports/policy_trigger_behavior_audit.json",
        "markdown_path": "analysis/reports/policy_trigger_behavior_audit.md",
        "quality_path": "analysis/reports/policy_trigger_behavior_audit_quality_check.json",
    },
    {
        "id": "ranking_sensitive_scenario",
        "title": "Ranking-sensitive scenario report",
        "category": "diagnostic",
        "description": "Scenarios where ranking decisions may be sensitive.",
        "artifact_path": "analysis/reports/ranking_sensitive_scenario_report.json",
        "markdown_path": "analysis/reports/ranking_sensitive_scenario_report.md",
        "quality_path": "analysis/reports/ranking_sensitive_scenario_quality_check.json",
    },
    {
        "id": "ranking_sensitivity_explanation",
        "title": "Ranking sensitivity explanation",
        "category": "diagnostic",
        "description": "Explanation of ranking sensitivity and practical equivalence risks.",
        "artifact_path": "analysis/reports/ranking_sensitivity_explanation_report.json",
        "markdown_path": "analysis/reports/ranking_sensitivity_explanation_report.md",
        "quality_path": "analysis/reports/ranking_sensitivity_explanation_quality_check.json",
    },
    {
        "id": "scientific_validation_plan",
        "title": "Scientific validation plan",
        "category": "scientific_validation",
        "description": "Planned validation actions and methodological warnings.",
        "artifact_path": "analysis/reports/scientific_validation_plan.json",
        "markdown_path": "analysis/reports/scientific_validation_plan.md",
        "quality_path": "analysis/reports/scientific_validation_plan_quality_check.json",
    },
]


def read_json_file(
    path: Path,
    fallback: dict[str, Any] | None = None,
) -> dict[str, Any]:
    if not path.exists():
        return fallback or {}

    with path.open("r", encoding="utf-8") as file:
        payload = json.load(file)

    if isinstance(payload, dict):
        return payload

    return fallback or {}


def read_text_file(path: Path) -> str:
    if not path.exists():
        return ""

    return path.read_text(encoding="utf-8")


def path_exists_as_bool(path: Path) -> bool:
    return path.exists() and path.is_file()


def quality_passed_from_payload(payload: dict[str, Any]) -> bool | None:
    for key in [
        "passed",
        "all_required_checks_passed",
        "quality_gate_passed",
        "quality_check_passed",
    ]:
        value = payload.get(key)

        if isinstance(value, bool):
            return value

    return None


def read_json_resource(relative_path: str) -> dict[str, Any]:
    path = REPOSITORY_ROOT / relative_path

    if not path_exists_as_bool(path):
        return {
            "path": relative_path,
            "exists": False,
            "loaded": False,
            "data": None,
            "error": "missing_file",
        }

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        return {
            "path": relative_path,
            "exists": True,
            "loaded": False,
            "data": None,
            "error": f"invalid_json: {error}",
        }

    return {
        "path": relative_path,
        "exists": True,
        "loaded": isinstance(payload, dict),
        "data": payload if isinstance(payload, dict) else None,
        "error": None if isinstance(payload, dict) else "json_root_is_not_object",
    }


def read_text_resource(relative_path: str) -> dict[str, Any]:
    path = REPOSITORY_ROOT / relative_path

    if not path_exists_as_bool(path):
        return {
            "path": relative_path,
            "exists": False,
            "loaded": False,
            "text": "",
            "error": "missing_file",
        }

    return {
        "path": relative_path,
        "exists": True,
        "loaded": True,
        "text": path.read_text(encoding="utf-8"),
        "error": None,
    }


def known_reports() -> list[dict[str, Any]]:
    reports: list[dict[str, Any]] = []

    for item in REPORT_DEFINITIONS:
        artifact_path = REPOSITORY_ROOT / item["artifact_path"]
        markdown_path = REPOSITORY_ROOT / item["markdown_path"]
        quality_path = REPOSITORY_ROOT / item["quality_path"]
        quality_payload = read_json_file(quality_path)

        reports.append(
            {
                **item,
                "available": path_exists_as_bool(artifact_path),
                "loaded": path_exists_as_bool(artifact_path),
                "markdown_available": path_exists_as_bool(markdown_path),
                "quality_available": path_exists_as_bool(quality_path),
                "quality_passed": quality_passed_from_payload(quality_payload),
            }
        )

    return reports


def report_definition_by_id(report_id: str) -> dict[str, str] | None:
    for item in REPORT_DEFINITIONS:
        if item["id"] == report_id:
            return item

    return None


def routes() -> list[dict[str, str]]:
    return [
        {
            "method": "GET",
            "path": "/api/v1/health",
            "description": "Return API status and read-only mode.",
        },
        {
            "method": "GET",
            "path": "/api/v1/project-status",
            "description": "Return the current project status report summary.",
        },
        {
            "method": "GET",
            "path": "/api/v1/reports",
            "description": "Return available generated reports and quality checks.",
        },
        {
            "method": "GET",
            "path": "/api/v1/reports/{id}",
            "description": "Return one known generated report by its safe report id.",
        },
        {
            "method": "GET",
            "path": "/api/v1/experimental-design-matrix",
            "description": "Return the experimental design matrix summary.",
        },
        {
            "method": "GET",
            "path": "/api/v1/research-method",
            "description": "Return the conservative research method framing and contract.",
        },
        {
            "method": "GET",
            "path": "/api/v1/simulation-state-contract",
            "description": "Return the conservative simulation state contract without enabling execution.",
        },
    ]


def health_payload() -> dict[str, Any]:
    return {
        "service": "fieldops_lab_api",
        "status": "ok",
        "mode": "read_only",
        "read_only": True,
        "allows_arbitrary_command_execution": False,
        "contract": {
            "available": path_exists_as_bool(PLATFORM_CONTRACT_PATH),
            "path": "platform/contracts/fieldops_platform_contract.json",
        },
        "research_method_contract": {
            "available": path_exists_as_bool(RESEARCH_METHOD_CONTRACT_PATH),
            "path": "platform/contracts/research_method_contract.json",
        },
        "simulation_state_contract": {
            "available": path_exists_as_bool(SIMULATION_STATE_CONTRACT_PATH),
            "path": "platform/contracts/simulation_state_contract.json",
        },
        "routes": routes(),
    }


def project_status_payload() -> dict[str, Any]:
    payload = read_json_file(PROJECT_STATUS_PATH)

    if payload:
        return {
            "report": "project_status",
            "available": True,
            "read_only": True,
            "source": {
                "exists": path_exists_as_bool(PROJECT_STATUS_PATH),
                "loaded": path_exists_as_bool(PROJECT_STATUS_PATH),
                "path": "analysis/reports/project_status_report.json",
            },
            "conservative_note": payload.get(
                "conservative_note",
                "This dashboard does not prove scientific validity.",
            ),
            **payload,
        }

    return {
        "report": "project_status",
        "available": False,
        "read_only": True,
        "summary_metrics": {
            "product_completeness": 57,
            "engineering_status": "report_unavailable",
            "scientific_status": "diagnostic_only_with_methodological_warnings",
        },
        "conservative_note": "Project status report is not available.",
    }


def experimental_design_payload() -> dict[str, Any]:
    payload = read_json_file(EXPERIMENTAL_DESIGN_PATH)

    if payload:
        return payload

    return {
        "report": "experimental_design_matrix",
        "available": False,
        "read_only": True,
        "summary": {
            "experiment_count": 0,
            "scenario_count": 0,
            "replication_count": 0,
            "reproducible_from_explicit_factors": False,
        },
    }


def reports_payload() -> dict[str, Any]:
    return {
        "read_only": True,
        "execution_supported": False,
        "write_operations_supported": False,
        "reports_root": "analysis/reports",
        "reports": known_reports(),
    }


def report_detail_payload(report_id: str) -> tuple[int, dict[str, Any]]:
    report_definition = report_definition_by_id(report_id)

    if report_definition is None:
        return HTTPStatus.NOT_FOUND, {
            "error": "report_not_found",
            "read_only": True,
            "available": False,
            "id": report_id,
            "known_report_ids": [item["id"] for item in REPORT_DEFINITIONS],
        }

    artifact = read_json_resource(report_definition["artifact_path"])
    markdown = read_text_resource(report_definition["markdown_path"])
    quality_check = read_json_resource(report_definition["quality_path"])

    quality_payload = (
        quality_check["data"] if isinstance(quality_check["data"], dict) else {}
    )

    return HTTPStatus.OK, {
        "report": "report_detail",
        "id": report_definition["id"],
        "title": report_definition["title"],
        "category": report_definition["category"],
        "description": report_definition["description"],
        "read_only": True,
        "execution_supported": False,
        "write_operations_supported": False,
        "available": artifact["loaded"],
        "metadata": {
            **report_definition,
            "quality_passed": quality_passed_from_payload(quality_payload),
        },
        "artifact": artifact,
        "markdown": markdown,
        "quality_check": quality_check,
        "conservative_note": (
            "This endpoint exposes generated report artifacts for inspection only. "
            "It does not execute experiments, solvers, scripts, or commands."
        ),
    }


def research_method_payload() -> dict[str, Any]:
    contract = read_json_file(RESEARCH_METHOD_CONTRACT_PATH)
    framing = read_text_file(RESEARCH_FRAMING_PATH)

    return {
        "read_only": True,
        "available": bool(contract) or bool(framing),
        "contract_path": "platform/contracts/research_method_contract.json",
        "framing_path": "platform/research_framing.md",
        "contract": contract,
        "framing_markdown": framing,
        "conservative_interpretation": {
            "does_not_claim_final_scientific_validity": True,
            "fuzzy_logic_is_optional": True,
            "practical_equivalence_must_be_handled": True,
            "real_company_data_requires_validation_before_decision_support": True,
        },
    }


def simulation_state_contract_payload() -> dict[str, Any]:
    contract = read_json_file(SIMULATION_STATE_CONTRACT_PATH)
    conservative = contract.get("conservative_interpretation", {})

    return {
        "read_only": True,
        "available": bool(contract),
        "contract_path": "platform/contracts/simulation_state_contract.json",
        "contract": contract,
        "conservative_interpretation": {
            "is_visual_simulation_implemented": bool(
                conservative.get("is_visual_simulation_implemented", False)
            ),
            "is_real_time_map_implemented": bool(
                conservative.get("is_real_time_map_implemented", False)
            ),
            "allows_browser_triggered_execution": bool(
                conservative.get("allows_browser_triggered_execution", False)
            ),
            "allows_arbitrary_command_execution": bool(
                conservative.get("allows_arbitrary_command_execution", False)
            ),
            "supports_user_delay_injection_in_ui_now": bool(
                conservative.get("supports_user_delay_injection_in_ui_now", False)
            ),
            "defines_future_safe_contract_only": bool(
                conservative.get("defines_future_safe_contract_only", False)
            ),
        },
        "conservative_note": (
            "This endpoint exposes the planned simulation state contract for inspection only. "
            "It does not start simulations, submit jobs, execute solvers, or inject user events."
        ),
    }


def route_payload(path: str) -> tuple[int, dict[str, Any]]:
    normalized_path = path.rstrip("/") or "/"

    if normalized_path == "/api/v1/health":
        return HTTPStatus.OK, health_payload()

    if normalized_path == "/api/v1/project-status":
        return HTTPStatus.OK, project_status_payload()

    if normalized_path == "/api/v1/reports":
        return HTTPStatus.OK, reports_payload()

    if normalized_path.startswith("/api/v1/reports/"):
        report_id = urllib.parse.unquote(
            normalized_path.removeprefix("/api/v1/reports/")
        )

        if not report_id or "/" in report_id:
            return HTTPStatus.NOT_FOUND, {
                "error": "report_not_found",
                "read_only": True,
                "available": False,
                "id": report_id,
                "known_report_ids": [item["id"] for item in REPORT_DEFINITIONS],
            }

        return report_detail_payload(report_id)

    if normalized_path == "/api/v1/experimental-design-matrix":
        return HTTPStatus.OK, experimental_design_payload()

    if normalized_path == "/api/v1/research-method":
        return HTTPStatus.OK, research_method_payload()

    if normalized_path == "/api/v1/simulation-state-contract":
        return HTTPStatus.OK, simulation_state_contract_payload()

    return HTTPStatus.NOT_FOUND, {
        "error": "not_found",
        "read_only": True,
        "path": path,
    }


class FieldOpsRequestHandler(BaseHTTPRequestHandler):
    server_version = "FieldOpsLabReadOnlyAPI/0.1"

    def log_message(self, format: str, *args: Any) -> None:
        return

    def send_json(self, status_code: int, payload: dict[str, Any]) -> None:
        body = json.dumps(payload, indent=2, sort_keys=True).encode("utf-8")

        self.send_response(status_code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "http://127.0.0.1:5173")
        self.send_header("Access-Control-Allow-Methods", "GET, HEAD, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Accept")
        self.end_headers()

        if self.command != "HEAD":
            self.wfile.write(body)

    def do_OPTIONS(self) -> None:
        self.send_response(HTTPStatus.NO_CONTENT)
        self.send_header("Access-Control-Allow-Origin", "http://127.0.0.1:5173")
        self.send_header("Access-Control-Allow-Methods", "GET, HEAD, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Accept")
        self.end_headers()

    def do_HEAD(self) -> None:
        status_code, payload = route_payload(self.path.split("?", 1)[0])
        self.send_json(status_code, payload)

    def do_GET(self) -> None:
        status_code, payload = route_payload(self.path.split("?", 1)[0])
        self.send_json(status_code, payload)

    def do_POST(self) -> None:
        self.send_json(
            HTTPStatus.METHOD_NOT_ALLOWED,
            {
                "error": "method_not_allowed",
                "read_only": True,
                "write_operations_supported": False,
                "execution_supported": False,
                "allows_arbitrary_command_execution": False,
                "allowed_methods": ["GET", "HEAD", "OPTIONS"],
            },
        )

    def do_PUT(self) -> None:
        self.do_POST()

    def do_PATCH(self) -> None:
        self.do_POST()

    def do_DELETE(self) -> None:
        self.do_POST()


def create_server(host: str, port: int, quiet: bool = False) -> ThreadingHTTPServer:
    return ThreadingHTTPServer((host, port), FieldOpsRequestHandler)


def read_url_json(url: str) -> tuple[int, dict[str, Any]]:
    request = urllib.request.Request(url, method="GET")

    try:
        with urllib.request.urlopen(request, timeout=5) as response:
            payload = json.loads(response.read().decode("utf-8"))
            return response.status, payload
    except urllib.error.HTTPError as error:
        try:
            payload = json.loads(error.read().decode("utf-8"))
            return error.code, payload
        finally:
            error.close()


def read_url_status_for_method(url: str, method: str) -> int:
    request = urllib.request.Request(url, method=method)

    try:
        with urllib.request.urlopen(request, timeout=5) as response:
            return response.status
    except urllib.error.HTTPError as error:
        try:
            return error.code
        finally:
            error.close()


def run_self_test() -> int:
    host = "127.0.0.1"
    server = create_server(host, 0)
    port = int(server.server_address[1])
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()

    try:
        base_url = f"http://{host}:{port}"

        expected_paths = [
            "/api/v1/health",
            "/api/v1/project-status",
            "/api/v1/reports",
            "/api/v1/reports/project_status",
            "/api/v1/reports/campaign_final_diagnostic_report",
            "/api/v1/experimental-design-matrix",
            "/api/v1/research-method",
            "/api/v1/simulation-state-contract",
        ]

        for path in expected_paths:
            status, payload = read_url_json(base_url + path)
            print(path, status)

            if status != HTTPStatus.OK:
                raise RuntimeError(f"Expected HTTP 200 for {path}, got {status}")

            if not payload.get("read_only", True):
                raise RuntimeError(f"Endpoint {path} did not preserve read-only contract")

        reports_status, reports_payload_data = read_url_json(base_url + "/api/v1/reports")

        if reports_status != HTTPStatus.OK:
            raise RuntimeError("Reports catalog endpoint is unavailable")

        report_ids = {
            report["id"]
            for report in reports_payload_data.get("reports", [])
            if isinstance(report, dict)
        }

        required_report_ids = {
            "campaign_index",
            "campaign_execution_index",
            "campaign_final_diagnostic_report",
            "campaign_result_summary",
            "full_campaign_pipeline",
        }

        missing_report_ids = required_report_ids - report_ids

        if missing_report_ids:
            raise RuntimeError(
                f"Reports catalog is missing campaign reports: {sorted(missing_report_ids)}"
            )

        detail_status, detail_payload = read_url_json(
            base_url + "/api/v1/reports/campaign_final_diagnostic_report"
        )

        if detail_status != HTTPStatus.OK:
            raise RuntimeError("Campaign final diagnostic report detail is unavailable")

        if detail_payload.get("id") != "campaign_final_diagnostic_report":
            raise RuntimeError("Report detail endpoint returned an unexpected campaign id")

        unknown_report_status = read_url_status_for_method(
            base_url + "/api/v1/reports/unknown_report",
            "GET",
        )
        print("GET /api/v1/reports/unknown_report", unknown_report_status)

        if unknown_report_status != HTTPStatus.NOT_FOUND:
            raise RuntimeError("Unknown report detail should return 404")

        post_status = read_url_status_for_method(base_url + "/api/v1/health", "POST")
        print("POST /api/v1/health", post_status)

        if post_status != HTTPStatus.METHOD_NOT_ALLOWED:
            raise RuntimeError("POST request should be rejected with 405")

        research_status, research_payload_data = read_url_json(
            base_url + "/api/v1/research-method"
        )

        if research_status != HTTPStatus.OK:
            raise RuntimeError("Research method endpoint is unavailable")

        research_conservative = research_payload_data.get(
            "conservative_interpretation", {}
        )

        if research_conservative.get("fuzzy_logic_is_optional") is not True:
            raise RuntimeError("Research method endpoint must keep fuzzy logic optional")

        if research_conservative.get("practical_equivalence_must_be_handled") is not True:
            raise RuntimeError("Research method endpoint must handle practical equivalence")

        simulation_status, simulation_payload_data = read_url_json(
            base_url + "/api/v1/simulation-state-contract"
        )

        if simulation_status != HTTPStatus.OK:
            raise RuntimeError("Simulation state contract endpoint is unavailable")

        simulation_conservative = simulation_payload_data.get(
            "conservative_interpretation", {}
        )

        if simulation_conservative.get("allows_browser_triggered_execution") is not False:
            raise RuntimeError("Simulation endpoint must not allow browser execution")

        if simulation_conservative.get("allows_arbitrary_command_execution") is not False:
            raise RuntimeError("Simulation endpoint must not allow arbitrary commands")

        if simulation_conservative.get("defines_future_safe_contract_only") is not True:
            raise RuntimeError("Simulation endpoint must expose contract-only status")

        print("FieldOps Lab read-only API self-test passed.")
        return 0
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)


def main() -> None:
    parser = argparse.ArgumentParser(description="FieldOps Lab read-only local HTTP API.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8080)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        raise SystemExit(run_self_test())

    server = create_server(args.host, args.port)

    print(f"FieldOps Lab read-only API listening on http://{args.host}:{args.port}")
    print("Allowed methods: GET, HEAD, OPTIONS")
    print("Execution endpoints are intentionally disabled.")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        print("Stopping FieldOps Lab read-only API server.")
        server.server_close()
        time.sleep(0.1)


if __name__ == "__main__":
    main()