import { StatusCard } from "../components/StatusCard";
import { formatToken } from "../domain/platform";
import { useDashboardViewModel } from "../viewModels/useDashboardViewModel";

export function ScientificValidationPage() {
  const viewModel = useDashboardViewModel();

  if (viewModel.loading) {
    return (
      <section className="section-card">
        <p className="eyebrow">Scientific validation</p>
        <h2>Loading validation status...</h2>
      </section>
    );
  }

  if (viewModel.error || !viewModel.snapshot) {
    return (
      <section className="section-card error-card">
        <p className="eyebrow">Scientific validation</p>
        <h2>Validation status unavailable</h2>
        <p>{viewModel.error ?? "Snapshot unavailable."}</p>
        <button className="primary-action" onClick={viewModel.reload} type="button">
          Retry
        </button>
      </section>
    );
  }

  const { snapshot } = viewModel;

  return (
    <>
      <section className="hero-card compact">
        <div>
          <p className="eyebrow">Scientific validation</p>
          <h2>Evidence and risk control</h2>
          <p className="hero-copy">
            This page keeps methodological limits visible while the platform is
            still diagnostic and engineering-focused.
          </p>
        </div>
      </section>

      <section className="status-grid">
        <StatusCard
          detail="Engineering quality gates can pass without proving research conclusions."
          label="Engineering status"
          value={formatToken(snapshot.status.engineeringStatus)}
        />
        <StatusCard
          detail="The research method still needs stronger statistical and external validation."
          label="Scientific status"
          value={formatToken(snapshot.status.scientificStatus)}
        />
        <StatusCard
          detail="Experiment factors are explicitly generated by the design matrix."
          label="Experimental design"
          value={`${snapshot.experimentalDesign.experimentCount} planned experiments`}
        />
      </section>

      <section className="section-card">
        <div className="section-heading">
          <div>
            <p className="eyebrow">Warnings</p>
            <h2>Conservative scientific interpretation</h2>
          </div>
        </div>

        <div className="warning-list">
          {snapshot.warnings.map((warning) => (
            <article className="warning-card warning" key={warning}>
              <strong>warning</strong>
              <p>{warning}</p>
            </article>
          ))}
        </div>
      </section>
    </>
  );
}